name: bewell_pro_core
description: Main package for Slade Advantage
version: 2.0.3
homepage: https://github.com/savannahghi/bewell_pro_core
repository: https://github.com/savannahghi/bewell_pro_core
issue_tracker: https://github.com/savannahghi/bewell_pro_core/issues
documentation: https://github.com/savannahghi/bewell_pro_core/blob/main/doc/readme.md

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  async_redux: ^18.0.2
  cached_network_image: ^3.0.0
  camera: ^0.10.0+4
  connectivity_plus: ^2.3.9
  country_pickers: ^2.0.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety
  debug_logger: ^0.0.23
  device_info: ^2.0.2
  dotted_border: ^2.0.0
  equatable: ^2.0.3
  fake_async: ^1.2.0
  file: ^6.1.0
  firebase_analytics: ^10.1.0
  firebase_auth_mocks: ^0.9.3
  firebase_core: ^2.3.0
  firebase_core_platform_interface: ^4.5.2
  firebase_crashlytics: ^3.0.10
  firebase_messaging: ^14.1.1
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.2
  flutter_local_notifications: ^12.0.4
  flutter_slidable: ^0.6.0
  flutter_svg: ^1.0.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  google_fonts: ^3.0.1
  html: ^0.15.0
  http: ^0.13.3
  image_picker: ^0.8.5+3
  import_sorter: ^4.6.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  material_design_icons_flutter: ^6.0.7096
  path: ^1.8.0
  permission_handler: ^9.2.0
  permission_handler_platform_interface: ^3.6.1
  photo_view: ^0.14.0
  plugin_platform_interface: ^2.0.1
  quiver: ^3.0.1
  rxdart: ^0.27.1
  sentry_flutter: ^6.9.1
  sghi_core: ^0.2.12
  shimmer: ^2.0.0
  sqflite: ^2.0.0+4
  unicons: ^2.0.1
  url_launcher: ^6.0.6

dev_dependencies:
  build_runner: ^2.0.4
  built_value_generator: ^8.0.2
  connectivity_platform_interface: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: 1.5.3
  mockito: ^5.0.1
  mocktail_image_network: ^0.3.1
  test: ^1.16.5
  url_launcher_platform_interface: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/
