name: bewell_pro_core
description: Main package for BeWell-Professional
version: 1.1.7-nullsafety
homepage: https://github.com/savannahghi/bewell_pro_core
repository: https://github.com/savannahghi/bewell_pro_core
issue_tracker: https://github.com/savannahghi/bewell_pro_core/issues
documentation: https://github.com/savannahghi/bewell_pro_core/blob/main/doc/readme.md

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  app_wrapper: ^0.1.23 # internal (formerly sil_app_wrapper)
  async_redux: ^12.0.0
  cached_network_image: ^3.0.0
  camera: ^0.8.1+3
  connectivity_plus: ^1.0.6
  country_pickers: ^2.0.0 # A country picker dropdown
  cupertino_icons: ^1.0.3
  dart_fcm: ^0.0.23 # internal (formerly sil_fcm)
  dartz: ^0.10.0-nullsafety
  debug_logger: ^0.0.23 # internal (formerly sil_logger)
  device_info: ^2.0.2
  domain_objects: ^0.0.27-nullsafety # internal (formerly sil_core_domain_objects)
  dotted_border: ^2.0.0 # Adds a dotted border around a card or container
  equatable: ^2.0.3
  fake_async: ^1.2.0
  file: ^6.1.0
  firebase_analytics: ^8.1.1
  firebase_auth_mocks: ^0.6.0
  firebase_core: ^1.2.1
  firebase_core_platform_interface: ^4.0.1
  firebase_crashlytics: ^2.0.5
  firebase_messaging: ^10.0.4
  # the flutter SDK
  flutter:
    sdk: flutter
  flutter_graphql_client: ^0.1.23 # internal (formerly sil_graphql_client)
  flutter_html: ^2.0.0
  flutter_local_notifications: ^8.0.0
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0 # used to render svg images
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  google_fonts: ^2.0.0
  html: ^0.15.0
  http: ^0.13.3
  image_picker: ^0.8.0+1 # For taking pictures with the camera
  image_picker_platform_interface: ^2.2.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  material_design_icons_flutter: ^5.0.5955-rc.1
  misc_utilities: ^0.1.27-nullsafety # internal (formerly sil_misc)
  path: ^1.8.0
  permission_handler: ^6.1.0
  permission_handler_platform_interface: ^3.6.1
  photo_view: ^0.11.1
  plugin_platform_interface: ^2.0.1
  quiver: ^3.0.1
  rxdart: ^0.27.1
  sentry_flutter: ^5.1.0
  shared_themes: ^0.1.0 # internal (formerly shared_themes)
  shared_ui_components: ^0.1.37-nullsafety # internal (formerly sil_ui_components)
  shimmer: ^2.0.0
  sqflite: ^2.0.0+4
  unicons: ^2.0.1
  url_launcher: ^6.0.6
  user_feed: ^0.1.39-nullsafety # internal (formerly sil_feed)
  user_profile: ^0.1.21-nullsafety # internal (formerly user_profile)

dev_dependencies:
  build_runner: ^2.0.4
  built_value_generator: ^8.0.2
  connectivity_platform_interface: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mockito: ^5.0.1
  mocktail_image_network: ^0.1.0
  test: ^1.16.5
  url_launcher_platform_interface: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/
