name: bewell_pro_core CI/CD Workflow

on: [push]

jobs: 
  run-tests-and-coverage: 
    name: Analyze, test and report coverage
    runs-on: ubuntu-latest
    timeout-minutes: 80
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12'
      - uses: actions/setup-python@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.0.3'

      - name: Install flutter dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Analyze and Test
        run: |
          flutter analyze
          flutter test --coverage test/
          sudo apt-get install -y lcov
          lcov --remove coverage/lcov.info 'lib/**/*.g.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/**/*.freezed.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/**/*.gr.dart' -o coverage/lcov.info
          lcov --remove coverage/lcov.info 'lib/infrastructure/repository/sqlite.dart' -o coverage/lcov.info  
          genhtml -q -o coverage coverage/lcov.info
          pip3 install lxml
          pip3 install beautifulsoup4
          python3 check_coverage.py

